module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  backup_migrate: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  breakpoint: 0
  ckeditor: 0
  coffee: 0
  color: 0
  comment: 0
  config: 0
  config_filter: 0
  contact: 0
  contact_block: 0
  contact_storage: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gavias_blockbuilder: 0
  gavias_sliderlayer: 0
  gavias_view: 0
  gaviasthemer: 0
  help: 0
  history: 0
  image: 0
  image_url_formatter: 0
  inline_entity_form: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  pathauto: 0
  profile: 0
  rdf: 0
  search: 0
  shortcut: 0
  simplenews: 0
  smtp: 0
  state_machine: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twitter_block: 0
  update: 0
  user: 0
  views_infinite_scroll: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  gavias_savor: 0
profile: standard
