features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 0
  path: themes/gavias_savor/favicon.ico
  mimetype: image/vnd.microsoft.icon
theme_skin: ''
enable_customize: '1'
sticky_menu: '1'
site_layout: wide
list_page_layout_boxed: ''
preloader: '0'
default_header: header
option_header: "/node/124---header-2\r\n/node/123---header-3"
footer_first_size: '12'
footer_second_size: '3'
footer_third_size: '3'
footer_four_size: '3'
customize_css: ''
